

services:
  app:
    build: .
    image: techtrackrregistry0c626d.azurecr.io/tracktech:v0.0.3
    container_name: techtrackr-app
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
